apiVersion: batch/v1
kind: CronJob
metadata:
  name: scrape-products-producer
spec:
  schedule: "2 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scrape-products-producer
            image: scrape-products:latest
          restartPolicy: OnFailure
